CREATE TABLE `lov_nannies`.`tag` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `uid` CHAR(8) NOT NULL , `target` VARCHAR(100) NOT NULL , `name` VARCHAR(300) NOT NULL , `info` TEXT NULL , `created_at` INT UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `lov_nannies`.`user_tag` ( `id` INT UNSIGNED NOT NULL AUTO_INCREMENT , `user_id` INT(11) NOT NULL , `tag_id` INT UNSIGNED NOT NULL , `created_at` INT UNSIGNED NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `user_tag` ADD FOREIGN KEY (`tag_id`) REFERENCES `tag`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `user_tag` ADD FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;